version: '3.3'

services:
  main:
    container_name: cryptocurrencyconvector
    env_file:
      - .production.env
    restart: always
    build: .
    ports:
      - "3000:3000"
    command:
      npm start